# Automatically generated by configure - do not modify

all:
SRC_PATH=/home/vboxuser/Desktop/qemu
TARGET_DIRS=aarch64-softmmu
GDB=/usr/bin/gdb
SUBDIRS= contrib/plugins
PYTHON=/home/vboxuser/Desktop/qemu/build-net/pyvenv/bin/python3 -B
MKVENV_ENSUREGROUP=/home/vboxuser/Desktop/qemu/build-net/pyvenv/bin/python3 -B /home/vboxuser/Desktop/qemu/python/scripts/mkvenv.py ensuregroup  --online
GENISOIMAGE=/usr/bin/genisoimage
MESON=/home/vboxuser/Desktop/qemu/build-net/pyvenv/bin/meson
NINJA=/usr/bin/ninja
EXESUF=
TCG_TESTS_TARGETS=
